### ISSUE TITLE
Choices which pop-up messages instead of changing the page don't change status (to be unclickable) until the next page refresh.

### ISSUE THREAD

**Issue by mparq** [sci-sim/sci-sim#18]
Clicking them does increment the number of visits on the page though.

**Comment by calebdre** [comment]
This is because the page never 'refreshes' like it does when it moves to another page then back again. Would quick fix would be to manually change it's state in the html?  
Any other fix ideas?

**Comment by mparq** [comment]
That would be a quick fix. There seems like there should be a better way to handle this, but for now I'll change the button to disabled after the processBinaryClick method completes to handle this specific bug. Maybe this can be reopened for refactoring somewhere down the line.

**Comment by calebdre** [comment]
fix #17 and fix #18
