### ISSUE TITLE
Abstract & Implement visit checker

### ISSUE THREAD

**Issue by calebdre** [sci-sim/sci-sim#23]
The page controller keeps track of how many times the user has been on a page via the `visits` and `minimum_choices` member variable. It attaches a button allowing the user to move on after a certain number of visits (minimum_choices) that comes from the API. We need to abstract this away and implement it in the Patient Engine.

**Comment by mparq** [comment]
Looking at the PatientEngine, it seems like the best way to do this would be to have some sort of data structure that keeps track of the page contexts we've already gotten mapped to page_ids. Perhaps we could work this into PageChain? Reasoning: If we call renderPage on a page_id that we've already rendered, should we really be making a new api request to get the same information we got before?

This way, if we call renderPage on a page_id that we've already rendered, we can just increment a visits field within the page context associated with that page_id. The tricky part here is making sure our PageRenderer composes the page as we expect. Right now, this is sort of built into our api call's done callback. Before I start working on that, does this seem like a good approach to you? I'm not sure how much work it would take to create this data structure / work it into PageChain. Working it into PageChain would probably be cleaner but will take more refactoring.

**Comment by mparq** [comment]
Oops, nevermind. I should have fetched from upstream first.

**Comment by mparq** [comment]
Where can I find the code that actually adds the button based on minimum choices right now? Or is that not yet implemented in PatientEngine?

**Comment by calebdre** [comment]
It's not in the PatientEngine at all. I got to that point and realized that you had a ticket for it so I used that as a stopping point.

**Comment by mparq** [comment]
Got it. I found the code I was looking for in the old PageController.

**Comment by mparq** [comment]
Looking at this code, I'm wondering if we need a dedicated VisitChecker. What if we just made a new field in page_context on first render called "visits". On every subsequent render of that already visited page, we increment visits. We would do this before calling renderer.composePage(). Would you have any qualms with the Renderer being in charge of adding the minimum-choices-button to the page based on the existence of the page context's "minimum_choices" field and comparing it to the value of its "visits" field? This seems like a job Renderer should be able to do, and incrementing the visits field on page restoration seems like a job PatientEngine can do without much issue.

**Comment by calebdre** [comment]
Sounds good! Do it!

**Comment by mparq** [comment]
Quick question. In the code for restorePage, we apply Patient Page directives to the page context again. Is there a need to do this. Will these ever change?

**Comment by calebdre** [comment]
I actually haven't tested with it not being there - it may not be necessary. I just assumed so, but that's definitely something to look in to.

**Comment by mparq** [comment]
I left it for now. Submitted a pull request.
