### ISSUE TITLE
Create SQL queries/script methods to transform/migrate the database

### ISSUE THREAD

**Issue by calebdre** [sci-sim/sci-sim#51]
Right now we can't use db_create. We'll need another way to load and edit seed data into the database and remove test data

**Comment by calebdre** [comment]
check into http://alembic.readthedocs.org/en/latest/

**Comment by matthewbeckler** [comment]
I have used alembic on other flask projects, it generally works quite well
for doing database migrations when your models are changing over time. Just
be sure to add the migrations to the repository so they are tracked.
