### ISSUE TITLE
Can't add original entries to the labnotebook

### ISSUE THREAD

**Issue by calebdre** [sci-sim/sci-sim#7]
When you click the add new note button on the labnotebook, nothing happens

**Comment by mparq** [comment]
I've narrowed this issue down to the <input> tag placed in the <li> constructed when LabNotebook.prototype.addNoteField is called. Check the field variable created on this method call. Taking out the <input> tag causes a new create-note item to appear on click with just the Add and Cancel buttons. Any thoughts as to what's going wrong with the <input> here?

**Comment by mparq** [comment]
Ah, clicking the Make new Note button is also calling the removeInput function, which is removing our input as soon as we create it :(
